### ISSUE TITLE
I writed a spider using icnov-lite to decode the html what is gb2312 , and sometimes will have the following error 

### ISSUE THREAD

**Issue by Summerlve** [ashtuchkin/iconv-lite#101]
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
/usr/local/lib/node_modules/iconv-lite/encodings/dbcs-codec.js:452
    var newBuf = new Buffer(buf.length*2),
                               ^
TypeError: Cannot read property 'length' of undefined
    at DBCSDecoder.write (/usr/local/lib/node_modules/iconv-lite/encodings/dbcs-codec.js:452:32)
    at Object.decode (/usr/local/lib/node_modules/iconv-lite/lib/index.js:38:23)
    at Request._callback (/Users/summer/Program/Lib/topWebsite/spider.js:81:21)
    at self.callback (/usr/local/lib/node_modules/request/request.js:354:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/usr/local/lib/node_modules/request/request.js:1011:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14

**Comment by ashtuchkin** [comment]
Yeah, I see you have a network error, then try to decode a 'null' buffer. You should check that the buffer is valid before calling `iconv.decode()`.

**Comment by Summerlve** [comment]
yes, it's the problem about network , sometime the network is bad , so the got null buffer. thx.
