### ISSUE TITLE
Error in the dbcs-codec when parsing japanese document (random error)

### ISSUE THREAD

**Issue by Nordes** [ashtuchkin/iconv-lite#161]
Hello,

I encountered an error that happen a bit randomly on one server I contact. I do a simple get to receive the data (Japanese encoding). I was wondering if it comes from the codec itself or if it was the 'request' module that was failing.

Here's the StackTrace
```
C:\my-app\node_modules\iconv-lite\encodings\dbcs-codec.js:453
    var newBuf = new Buffer(buf.length*2),
                               ^

TypeError: Cannot read property 'length' of undefined
    at DBCSDecoder.write (C:\my-app\node_modules\iconv-lite\encodings\dbcs-codec.js:453:32)
    at Object.decode (C:\my-app\node_modules\iconv-lite\lib\index.js:42:23)
    at Request._callback (C:\my-app\src\service\myProxyService.js:45:22)
    at self.callback (C:\my-app\node_modules\request\request.js:188:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\my-app\node_modules\request\request.js:884:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ashtuchkin** [comment]
Looks like the buffer that is passed to iconv.decode() is undefined. Maybe
HTTP request failed? You might want to add a check before calling
iconv.decode().

--
Alexander Shtuchkin

**Comment by Nordes** [comment]
Thank's, I'll do that.
