### ISSUE TITLE
Node warnings with --trace-sync-io

### ISSUE THREAD

**Issue by robcalcroft** [ashtuchkin/iconv-lite#169]
This lib appears to through lots of warnings when an app is run with `--trace-sync-io` could this have an impact on performance?

**Comment by ashtuchkin** [comment]
Interesting, I didn't know about this flag. Does it have anything other
than loading require()-d files?

**Comment by jumoog** [comment]
```
(node:21085) WARNING: Detected use of sync API
    at fs.closeSync (fs.js:548:11)
    at fs.readFileSync (fs.js:524:8)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:20)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /root/server_ota/node_modules/iconv-lite/encodings/index.js:12:5

```

**Comment by ashtuchkin** [comment]
​Yeah, iconv-lite only loads conversion tables when they are actually
requested, using regular `require()` mechanism. It is an optimization, so
that you don't pay the cost of ~200ms on every load of your app even if you
don't use iconv-lite. This warning is expected.

--
Alexander Shtuchkin
