### ISSUE TITLE
Fail to decode when prototype function added to Object

### ISSUE THREAD

**Issue by bestmike007** [ashtuchkin/iconv-lite#89]
In the following case iconv-lite fails.

``` coffeescript
Object.prototype.permits = -> ''
iconv = require "iconv-lite"
console.log iconv.decode(new Buffer("test"), 'gbk')
```

Stack:

```
TypeError: Cannot read property 'permits' of undefined
  at new DBCSCodec (/~/node_modules/iconv-lite/encodings/dbcs-codec.js:84:67)
  at Object.exports._dbcs (/~/node_modules/iconv-lite/encodings/dbcs-codec.js:7:12)
  at Object.getCodec (/~/node_modules/iconv-lite/lib/index.js:98:35)
  at Object.decode (/~/node_modules/iconv-lite/lib/index.js:34:25)
  at Object.<anonymous> (/~/test.coffee:3:19)
  at Object.<anonymous> (/~/test.coffee:1:1)
  at Module._compile (module.js:456:26)
```

[https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/dbcs-codec.js#L84](https://github.com/ashtuchkin/iconv-lite/blob/master/encodings/dbcs-codec.js#L84)

The monkey patch is bad, however in some cases it's preferred. Suggested solutions:

``` js
    // Add more encoding pairs when needed.
    var encodeAdd  = options.encodeAdd || {}
    for (var uChar in encodeAdd) {
        if (typeof(encodeAdd[uChar]) === 'function') continue;
        this._setEncodeChar(uChar.charCodeAt(0), encodeAdd[uChar]);
    }
```

**Comment by ashtuchkin** [comment]
This is so bad) You'd screw up any `for (in)` cycle with this. If the method is still needed, I'd recommend creating it as a non-enumerable property, like that:

```coffeescript
Object.defineProperty Object.prototype, "permits", {enumerable: false, value: -> ""}
```

Anyway, I made it work even with enumerable prop with soon-to-be-released version 0.4.7.
